#!/usr/bin/env php
<?php
require_once __DIR__ . '/../vendor/autoload.php';

use Src\Commands\CapitalGainsCommand;
use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new CapitalGainsCommand());
try {
    $app->run();
} catch (Exception $e) {
    echo $e->getMessage();
}